name: pgvibe

services:
  postgres:
    image: postgres:15-alpine
    container_name: pgvibe-postgres
    environment:
      POSTGRES_DB: pgvibe_test
      POSTGRES_USER: pgvibe_user
      POSTGRES_PASSWORD: pgvibe_password
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgvibe_user -d pgvibe_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

# Development helper services
networks:
  default:
    name: pgvibe-network
